# Generated by Django 5.2.7 on 2026-02-22 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional task description', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the task is completed')),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional task due date', null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='Task priority', max_length=10)),
                ('expire_at', models.DateTimeField(blank=True, help_text='Auto-expiry timestamp for cleanup', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['due_date'], name='todo_todo_due_dat_4529b3_idx'), models.Index(fields=['priority'], name='todo_todo_priorit_2dbd60_idx'), models.Index(fields=['completed'], name='todo_todo_complet_12feab_idx')],
            },
        ),
    ]
